name: testing
permissions:
  contents: read

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to test"
        type: string
        default: ""
        required: false
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - ".github/ISSUE_TEMPLATE/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: npm test
